- name: Query the existing partitions
  parted:
    device: '{{ target_disk }}'
    unit: MiB
  register: original_device_info
    
- name: Unmount any mounted partitions
  shell: 'swapoff {{ target_disk|quote }}{{ item.num }} || umount {{ target_disk|quote }}{{ item.num }} ||:'
  loop: '{{ original_device_info.partitions }}'

- name: Wipe the target device
  parted:
    device: '{{ target_disk }}'
    number: '{{ item.num }}'
    state: absent
  loop: '{{ original_device_info.partitions }}'

- name: Create the swap partition 
  parted:
    device: '{{ target_disk }}'
    number: 1
    state: present
    part_end: '{{ swap_partition_size }}'

- name: Create the root partition
  parted:
    device: '{{ target_disk }}'
    number: 2
    state: present
    flags: boot
    part_start: '{{ swap_partition_size }}'

- name: Format the swap partition
  filesystem:
    fstype: swap
    dev: '{{ target_disk }}1'
  changed_when: true

- name: Format the root partition
  filesystem:
    fstype: '{{ root_partition_type }}'
    dev: '{{ target_disk }}2'
  changed_when: true

